---
- name: Verify memory and cache sizes
  assert:
    that:
      - openethereum_cont_mem_limit|int > openethereum_cache_size|int
    fail_msg: 'Memory limit cant be lower than cache: {{ openethereum_cont_mem_limit }} > {{ openethereum_cache_size }}'
    success_msg: 'Memory limit is higher than cache size: {{ openethereum_cont_mem_limit }} > {{ openethereum_cache_size }}'
    quiet: true
