---
- name: Create container directories
  file:
    path: '{{ item }}'
    owner: dockremap
    group: docker
    state: directory
  with_items:
    - '{{ openethereum_service_path }}'
    - '{{ openethereum_cont_vol }}'

- name: Create Geth JSON RPC wrapper script
  template:
    src: 'rpc.sh.j2'
    dest: '{{ openethereum_service_path }}/rpc.sh'
    owner: 'root'
    group: 'docker'
    mode: 0750
